config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
  get 'about', to: 'pages#about'
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :articles do 
  	resources :comments
  	resources :likes
	end
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: { minimum: 1, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :verify_authenticity_token
  #skip_after_action :verify_authenticity_token 

  def new
      @article = Article.new
  end

  def create
      #render plain: params[:article].inspect
      # @article = Article.new(article_params)
      @article = current_user.articles.new(article_params)
      if @article.save!
        flash[:notice] = "Article was successfully created"
        redirect_to article_path(@article)
        #redirect_to @article
      else
        render 'new'
      end
  end

  def show
      @article = Article.find(params[:id])
      #puts @article.id
      @comment = Comment.new
      #@comment = @article.commments
      #@comment.article_id = @article.id
  end

  def edit
    @article = Article.find(params[:id])
    unless current_user == @article.user
      redirect_to(@article, notice: "You are not authorized to edit it") 
      flash[:error] = "You are not authorized to edit it"
      return
    end
  end
  
  def update
    @article = Article.find(params[:id])
        if @article.update(article_params)
          flash[:notice] = "Article was updated"
          redirect_to article_path(@article)
      else
        flash[:notice] = "Article was not updated"
        render 'edit'
      end
    end

  def destroy
      @article = Article.find(params[:id])
      if current_user == @article.user
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
      else
        return
      end
  end

  def index
      @articles = Article.all
      #@user = current_user
  end

  private
      def article_params
        params.require(:article).permit(:title, :description)
      end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<!-- TO DISPLAY ALL THE COMMENTS IN THE SHOW PAGE WITH EDIT & DELETE -->
<div id="comment-<%=comment.id%>">
	<div id="single_comment">
	    <h4>Comment by <%= comment.user.email%></h4> 
	    <p class="comment"><%= comment.description %></p>
	    <span class="dateandoptions">
		  Posted <%=time_ago_in_words(comment.created_at)%> ago <br/>
		  <%= button_to 'Delete', article_comment_path(@article, comment), method: :delete, remote: true %>
		  <%= button_to 'Edit', edit_article_comment_path(@article, comment), method: :get, remote: true %>
		</span>
	</div>
</div>

app/views/articles/_form.html.erb
<!-- TO DISPLAY ARTICLES IN THE SHOW PAGE INDIVIDUALLY -->
	<% if @article.errors.any? %>
		 <h2>The following errors prevented the article from saving:</h2>
	 	<ul>
	 		<% @article.errors.full_messages.each do |msg|%>
	 		<li><%= msg %></li>
	 		<% end %>
	 	</ul>
	<% end %>
	<%= form_for @article do |f| %>
		<p>
	  		<%= f.label :title %><br>
	  		<%= f.text_field :title %>
	 	</p>
	 	<p>
		  <%= f.label :description %><br>
		  <%= f.text_area :description %>
		</p>
	 	<p>
	  	   <%= f.submit %>
	 	</p>
	<% end %>
	<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<!--	<% if @article.errors.any? %>
	 <h2>The following errors prevented the article from saving:</h2>
		 <ul>
			 <% @article.errors.full_messages.each do |msg|%>
	 		<li><%= msg %></li>
	 		<% end %>
	 	</ul>
	<% end %>
-->
	
	<%= form_for @article do |f| %>
	<%= render 'form' %>
<% end %>

app/views/articles/index.html.erb
<div style="padding: 20px">
<h1>Listing all articles</h1>

<style type="text/css">
  dl {
    display: flex;
    flex-flow: row wrap;
    border: solid #333;
    border-width: 0px 0px 0 0;
  }
  dt {
    flex-basis: 20%;
    padding: 2px 4px;
    background: #333;
    text-align: right;
    color: #fff;
  }
  dd {
    flex-basis: 70%;
    flex-grow: 1;
    margin: 0;
    padding: 2px 4px;
    border-bottom: 0px solid #333;
  }
</style>


<%= link_to 'Create New Article', new_article_path, class:"btn btn-primary btn-sm" %>
<table>
 <!-- <tr>
  <th>Title</th>
  <th>Description</th>
 </tr> -->
 <% @articles.each do |article| %>
 <dl>
  <dt><%= article.title %></dt> 
 
  <dd><%= article.description %></dd>
 </dl>
 
 <tr>
  <td><%= link_to 'Edit', edit_article_path(article) %></td> 

  <td><%= link_to 'Show', article_path(article) %></td>  
  
  <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
 </tr>
 <br/>
</table>
 <% end %>
</table>
</div>


<!--
<button class="abc" id="qw">
  anant
</button>
<script type="text/javascript">
  $("#qw").click(function(){
    $("#qw").hide()
  })
</script>
-->

app/views/articles/new.html.erb
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 5, class: "form-control" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
<%= link_to 'Back', articles_path %>
 </div>
</div>

app/views/articles/show.html.erb
<div style="padding: 20px">
	<h1>Show Article</h1>
	<p>
		 <h3>Title:  <%= @article.title %> </h3>
	</p>
	<br/>
	<h4>
		<p>
	 		Description:  <%= @article.description %>
		</p>
	</h4>
	<br/>

	<%= link_to "Edit", edit_article_path(@article) %> &nbsp; &nbsp;
	<%= link_to 'Back', articles_path %> &nbsp; &nbsp;
	<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"} %>
	<br/>
	<div id="create-likes">
	<%= button_to 'Like', article_likes_path(@article), method: :article, class:"btn btn-primary",remote: true %>
	</div>
	<div id="likes-count">
	<%= @article.likes.count %> <%= (@article.likes.count) == 1 ? 'Like' : 'Likes'%>
	</div>
	<br/>

	<!-- TO DISPLAY ALL THE COMMENTS COMMENTS->_FORM.HTML.ERB -->
	<div id="create-comment">
	<%= render partial: 'comments/form', locals: {article: @article, comment: @comment} %> 
 	</div>
 	
	<div id="comments_count">
		<h3>Comments (<%= @article.comments.size %>)</h3>
	</div>

	<div id="article_comment">
	<%= render partial: 'articles/comment', locals: {comment: @comment}, collection: @article.comments.reverse %>
	</div>
</div>